---
- name: Copy interfaces configuration
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    backup: yes
  notify: reload networking
  tags:
    - interfaces

- name: Copy PoE configuration
  template:
    src: poe.j2
    dest: /etc/cumulus/poe.conf
    backup: yes
  when: env == "prod"
  notify: load PoE config
  tags:
    - interfaces
