---
node:
  netdw2-leaf-a3f:
    lo: 10.255.255.13/32
    mlag:
      primary: true
      members:
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.144.10
      sysmac: 44:38:39:FF:13:12
      priority: 4096
    bridge:
      native: 123
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp52
        trunk: true
      downlink:
        mlag: true
        mlag-id: 2
        members:
        - swp49
        trunk: true
      swp1:
        mlag: false
        trunk: true
        voip:
          data-vlan: 119
          voice-vlan: 120
        poe_prio: high
