---
env: prod

cl_license_server: 172.16.200.10
node_exporter_version: 0.16.0
public_ssh_key: http://172.16.200.2/authorized_keys

ntp:
  - '172.16.200.1'
  - '172.16.44.10'

timezone: 'Europe/Amsterdam'

snmp_ro_community: public
snmp_contact: infra@naturalis.nl
snmp_allowed_hosts:
  - 172.16.200.10/32
  - 172.16.200.20/32
