---
- name: Cumulus remove support files
  hosts: switches
  remote_user: cumulus
  gather_facts: no
  become: yes
  tasks:

    - name: determine newly created support file
      shell: ls -lt /var/support/cl_support* | head -n2 | tail -n1 | awk '{print $9}'
      register: new_support_file

    - name: Removing CL-Support files
      file:
        path: "{{ new_support_file.stdout }}"
        state: absent
      when: new_support_file.stdout.find('cl_support') != -1
...
