---
- name: Cumulus Switch provisioning
  hosts: switches
  remote_user: cumulus
  vars:
    check_ptm: false
    check_lldp: false
  gather_facts: yes
  become: yes
  roles:
    - ansible-cumulus-common
    - ansible-cumulus-metrics
    - ansible-cumulus-ptm

- name: Cumulus Setup interfaces for spine switches
  hosts: switches
  remote_user: cumulus
  gather_facts: no
  become: true
  roles:
    - ansible-cumulus-interfaces
...
