---
- name: Cumulus Setup interfaces for spine switches
  hosts: spine
  remote_user: cumulus
  gather_facts: no
  become: yes
  roles:
    - ansible-role-cumulus-spine

- name: Cumulus Setup interfaces for leaf switches
  hosts: leaf
  remote_user: cumulus
  gather_facts: no
  become: yes
  roles:
    - ansible-role-cumulus-leaf
...
