---
public_ssh_key: http://172.16.200.254/authorized_keys

node_exporter_version: 0.16.0
rsyslog_server: 172.16.200.2
rsyslog_port: 512
snmp_ro_community: public
snmp_location: Leiden
snmp_contact: infra@naturalis.nl
snmp_allowed_hosts:
  - 172.16.200.10/32
  - 172.16.200.20/32

ntp:
  - '172.16.200.1'
  - '172.16.44.10'

timezone: 'Europe/Amsterdam'

ptm:
  - '"netdw2-spine-a":"swp47" -- "uplink01":"swp1"'
  - '"netdw2-spine-a":"swp48" -- "uplink02":"swp1"'
  - '"netdw2-spine-b":"swp47" -- "uplink01":"swp2"'
  - '"netdw2-spine-b":"swp48" -- "uplink02":"swp2"'
  - '"netdw2-spine-a":"swp49" -- "netdw2-spine-b":"swp49"'
  - '"netdw2-spine-a":"swp50" -- "netdw2-spine-b":"swp50"'
  - '"netdw2-spine-a":"swp1" -- "netdw2-leaf-d1a":"swp52"'
  - '"netdw2-spine-b":"swp1" -- "netdw2-leaf-d1d":"swp52"'
  - '"netdw2-spine-a":"swp2" -- "netdw2-leaf-h1a":"swp52"'
  - '"netdw2-spine-b":"swp2" -- "netdw2-leaf-h1d":"swp52"'
  - '"netdw2-leaf-d1a":"swp50" -- "netdw2-leaf-d1d":"swp50"'
  - '"netdw2-leaf-d1a":"swp49" -- "netdw2-leaf-d1b":"swp49"'
  - '"netdw2-leaf-d1d":"swp49" -- "netdw2-leaf-d1c":"swp49"'
  - '"netdw2-leaf-d1b":"swp50" -- "netdw2-leaf-d1c":"swp50"'
  - '"netdw2-leaf-d1b":"swp1" -- "host01":"swp1"'
  - '"netdw2-leaf-d1c":"swp1" -- "host02":"swp1"'
  - '"netdw2-leaf-h1a":"swp50" -- "netdw2-leaf-h1d":"swp50"'
  - '"netdw2-leaf-h1a":"swp49" -- "netdw2-leaf-h1b":"swp49"'
  - '"netdw2-leaf-h1d":"swp49" -- "netdw2-leaf-h1c":"swp49"'
  - '"netdw2-leaf-h1b":"swp50" -- "netdw2-leaf-h1c":"swp50"'
  - '"netdw2-leaf-h1b":"swp1" -- "host03":"swp1"'
  - '"netdw2-leaf-h1c":"swp1" -- "host04":"swp1"'

node:
  uplink01:
    lo: 10.255.255.30/32
    ospf:
      router-id: 145.136.246.225
      lnk-vlan: 269
      members:
      - swp1
      - swp2
    ports:
      swp1:
        mlag: false
        trunk: false
        vlan: 269
      swp2:
        mlag: false
        trunk: false
        vlan: 269

  uplink02:
    lo: 10.255.255.31/32
    ospf:
      router-id: 145.136.246.226
      lnk-vlan: 269
      members:
      - swp1
      - swp2
    ports:
      swp1:
        mlag: false
        trunk: false
        vlan: 269
      swp2:
        mlag: false
        trunk: false
        vlan: 269

  netdw2-spine-a:
    lo: 10.255.255.1/32
    ospf:
      router-id: 145.136.246.227
      lnk-vlan: 269
      members:
      - swp47
      - swp48
    mlag:
      primary: true
      members:
      - swp49
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.200.10
      sysmac: 44:38:39:FF:01:12
      priority: 4096
    bridge:
      native: 122
      priority: 4096
    ports:
      ser-d:
        mlag: true
        mlag-id: 1
        members:
        - swp1
        trunk: true
      ser-h:
        mlag: true
        mlag-id: 2
        members:
        - swp2
        trunk: true
      swp47:
        mlag: false
        vlan: 269
        trunk: false
      swp48:
        mlag: false
        vlan: 269
        trunk: false

  netdw2-spine-b:
    lo: 10.255.255.2/32
    ospf:
      router-id: 145.136.246.228
      lnk-vlan: 269
      members:
      - swp47
      - swp48
    mlag:
      primary: false
      members:
      - swp49
      - swp50
      address: 169.254.1.2/30
      peer-ip: 169.254.1.1
      backup-ip: 192.168.200.8
      sysmac: 44:38:39:FF:01:12
      priority: 4096
    bridge:
      native: 122
      priority: 4096
    ports:
      ser-d:
        mlag: true
        mlag-id: 1
        members:
        - swp1
        trunk: true
      ser-h:
        mlag: true
        mlag-id: 2
        members:
        - swp2
        trunk: true
      swp47:
        mlag: false
        vlan: 269
        trunk: false
      swp48:
        mlag: false
        vlan: 269
        trunk: false

  netdw2-leaf-d1a:
    lo: 10.255.255.11/32
    mlag:
      primary: true
      members:
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.200.17
      sysmac: 44:38:39:FF:11:12
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp52
        trunk: true
      downlink:
        mlag: true
        mlag-id: 2
        members:
        - swp49
        trunk: true

  netdw2-leaf-d1d:
    lo: 10.255.255.12/32
    mlag:
      primary: false
      members:
      - swp50
      address: 169.254.1.2/30
      peer-ip: 169.254.1.1
      backup-ip: 192.168.200.16
      sysmac: 44:38:39:FF:11:12
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp52
        trunk: true
      downlink:
        mlag: true
        mlag-id: 2
        members:
        - swp49
        trunk: true

  netdw2-leaf-d1b:
    lo: 10.255.255.13/32
    mlag:
      primary: true
      members:
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.200.14
      sysmac: 44:38:39:FF:12:34
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp49
        trunk: true
      swp1:
        mlag: false
        trunk: true
        vlans:
        - 121
        - 122
        - 123
        poe: true

  netdw2-leaf-d1c:
    lo: 10.255.255.14/32
    mlag:
      primary: false
      members:
      - swp50
      address: 169.254.1.2/30
      peer-ip: 169.254.1.1
      backup-ip: 192.168.200.13
      sysmac: 44:38:39:FF:12:34
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp49
        trunk: true
      swp1:
        mlag: false
        trunk: true
        vlan: 123
        poe: true

  netdw2-leaf-h1a:
    lo: 10.255.255.21/32
    mlag:
      primary: true
      members:
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.200.5
      sysmac: 44:38:39:FF:21:12
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp52
        trunk: true
      downlink:
        mlag: true
        mlag-id: 2
        members:
        - swp49
        trunk: true

  netdw2-leaf-h1d:
    lo: 10.255.255.22/32
    mlag:
      primary: false
      members:
      - swp50
      address: 169.254.1.2/30
      peer-ip: 169.254.1.1
      backup-ip: 192.168.200.9
      sysmac: 44:38:39:FF:21:12
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp52
        trunk: true
      downlink:
        mlag: true
        mlag-id: 2
        members:
        - swp49
        trunk: true

  netdw2-leaf-h1b:
    lo: 10.255.255.23/32
    mlag:
      primary: true
      members:
      - swp50
      address: 169.254.1.1/30
      peer-ip: 169.254.1.2
      backup-ip: 192.168.200.7
      sysmac: 44:38:39:FF:22:34
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp49
        trunk: true
      swp1:
        mlag: false
        trunk: false
        vlan: 123

  netdw2-leaf-h1c:
    lo: 10.255.255.24/32
    mlag:
      primary: false
      members:
      - swp50
      address: 169.254.1.2/30
      peer-ip: 169.254.1.1
      backup-ip: 192.168.200.6
      sysmac: 44:38:39:FF:22:34
    bridge:
      native: 122
      priority: 4096
    ports:
      uplink:
        mlag: true
        mlag-id: 1
        members:
        - swp49
        trunk: true
      swp1:
        mlag: false
        trunk: false
        vlan: 123
