---
- name: Create node_exporter user
  user:
    name: node_exporter
    state: present
    shell: /bin/false
    system: no
    createhome: no

- name: Copy node_exporter file
  copy:
    src: node_exporter-{{ node_exporter_version }}-{{ ansible_architecture }}
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    mode: 0755
  notify: restart node_exporter

- name: Make systemd service for node_exporter
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter@mgmt.service
  notify: restart node_exporter

- name: Start node_exporter
  systemd:
    name: node_exporter@mgmt
    enabled: yes
    state: started
    daemon_reload: yes
