---
- name: Create node_exporter user
  user:
    name: node_exporter
    state: present
    shell: /bin/false
    system: no
    createhome: no

- name: Copy node_exporter file
  copy:
    src: node_exporter-{{ node_exporter_version }}-{{ ansible_architecture }}
    dest: /usr/local/bin/node_exporter
    owner: node_exporter
    group: node_exporter
    mode: 0755
  notify: restart node_exporter

- name: Make systemd service for node_exporter
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter@mgmt.service
  notify: restart node_exporter

- name: Start node_exporter
  systemd:
    name: node_exporter@mgmt
    enabled: yes
    state: started
    daemon_reload: yes

- name: Add remote syslog server
  lineinfile:
    path: /etc/rsyslog.d/11-remotesyslog.conf
    create: true
    line: "*.*   @{{ rsyslog_server }}:{{ rsyslog_port }}   # UDP"
  notify: restart rsyslog

- name: create and modify snmpd.conf
  template:
    src: snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    mode: 0644
  notify: restart snmpd

- name: enable snmpd at boottime
  service:
    name: snmpd
    enabled: yes
