---
- name: Create node_exporter user
     user:
      name: node-exporter
      state: present
      shell: /bin/false
      system: no
      createhome: no

- name: Copy node-exporter file
  copy:
    src: node-exporter-{{ node-exporter-version }}-amd64
    dest: /usr/local/bin/node-exporter
    owner: node_exporter
  when: ansible_architecture == "x86_64"
  notify: restart node-exporter

- name: Make systemd service for node-exporter
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/node_exporter.service
  notify: restart node-exporter

- name: Start node-exporter
    systemd:
      name: node-exporter
      enabled: yes
      state: started
      daemon_reload: yes
