---
- name: Cumulus Setup interfaces for spine switches
  hosts: core
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  roles:
    - cl-interface-spine

- name: Cumulus Setup interfaces for leaf switches
  hosts: access
  gather_facts: no
  become: true
  become_method: sudo
  become_user: root
  roles:
    - cl-interface-leaf
...
