---
- name: Cumulus Switch provisioning
  hosts: network
  remote_user: cumulus
  vars:
    check_ptm: false
    check_lldp: false
  gather_facts: yes
  become: yes
  roles:
    - cl-common
#    - cl-license
#    - cl-users
#    - cl-apt
#    - cl-ldap
#    - cl-rsyslog
#    - cl-snmp
#    - cl-ptm

- name: Cumulus Setup interfaces for spine switches
  hosts: spine
  remote_user: cumulus
  gather_facts: no
  become: yes
  roles:
    - cl-interface-spine

- name: Cumulus Setup interfaces for leaf switches
  hosts: leaf
  remote_user: cumulus
  gather_facts: no
  become: yes
  roles:
    - cl-interface-leaf
...
