---
- name: Cumulus Switch provisioning
  hosts: vx
  remote_user: cumulus
  gather_facts: yes
  become: yes
  vars:
    check_ptm: false
    check_lldp: false
    ansible_become_pass: "CumulusLinux!"

  roles:
    - cl-common
#    - cl-license
#    - cl-users
#    - cl-apt
#    - cl-ldap
#    - cl-rsyslog
#    - cl-snmp
#    - cl-ptm

- name: Cumulus Setup interfaces for spine switches
  hosts: vx-core
  remote_user: cumulus
  gather_facts: no
  become: yes
  vars:
    ansible_become_pass: "CumulusLinux!"

  roles:
    - cl-interface-spine

- name: Cumulus Setup interfaces for leaf switches
  hosts: vx-access
  remote_user: cumulus
  gather_facts: no
  become: yes
  vars:
    ansible_become_pass: "CumulusLinux!"
  roles:
    - cl-interface-leaf
...
