---
ptm:
  - '"sw005897-mgmt":"3" -- "netdw2-spine-a1a":"eth0"'
  - '"sw005897-mgmt":"4" -- "netdw2-leaf-a3f":"eth0"'
  - '"sw005897-mgmt":"5" -- "netdw2-leaf-a3b":"eth0"'
  - '"sw005897-mgmt":"6" -- "netdw2-leaf-a3c":"eth0"'
  - '"sw005897-mgmt":"7" -- "netdw2-leaf-a3e":"eth0"'
  - '"sw005897-mgmt":"8" -- "netdw2-leaf-a3d":"eth0"'
  - '"sw005897-mgmt":"9" -- "netdw2-leaf-a3a":"eth0"'
  - '"netdw2-spine-a1a":"swp1" -- "netdw2-leaf-a3a":"swp52"'
  - '"netdw2-spine-a1b":"swp1" -- "netdw2-leaf-a3b":"swp52"'
  - '"netdw2-leaf-a3a":"swp50" -- "netdw2-leaf-a3b":"swp50"'
  - '"netdw2-leaf-a3c":"swp50" -- "netdw2-leaf-a3f":"swp50"'
  - '"netdw2-leaf-a3d":"swp50" -- "netdw2-leaf-a3e":"swp50"'
  - '"netdw2-leaf-a3a":"swp49" -- "netdw2-leaf-a3f":"swp52"'
  - '"netdw2-leaf-a3b":"swp49" -- "netdw2-leaf-a3c":"swp52"'
  - '"netdw2-leaf-a3c":"swp49" -- "netdw2-leaf-a3d":"swp52"'
  - '"netdw2-leaf-a3f":"swp49" -- "netdw2-leaf-a3e":"swp52"'
