---
# Set common settings like NTP, Hostname, Timezone
  - name: Setup NTP remove default NTP servers
    lineinfile:
      path: /etc/ntp.conf
      state: absent
      regexp: "cumulusnetworks.pool.ntp.org"
    tags:
      - time_setup

  - name: Setup NTP servers
    lineinfile:
      path: /etc/ntp.conf
      state: present
      insertafter: "#server ntp.your-provider.example"
      line: "server {{item}}"
    with_items:
      - 172.16.200.2
      - 172.16.44.10
    tags:
      - time_setup

#  - name: ntp daemon state
#    shell: systemctl status ntp@mgmt
#    register: ntp_daemon_state
#    tags:
#      - time_setup

  - name: Configured NTP in management VRF
    command: "{{item}}"
    with_items:
      - systemctl stop ntp.service
      - systemctl disable ntp.service
      - systemctl enable ntp@mgmt
      - systemctl start ntp@mgmt
#    when:
#      - ntp_daemon_state.stdout.find('active (running)') == -1
    tags:
      - time_setup

  - name: set timezone to Europe/Amsterdam
    timezone:
      name: Europe/Amsterdam
    tags:
      - time_setup

  - name: Ensure a locale exists
    locale_gen:
      name: en_US.UTF-8
      state: present
    tags:
      - time_setup

  - name: Set default locale to en_US.UTF.8
    lineinfile:
      path: /etc/default/locale
      line: 'LC_ALL="en_US.UTF-8"'

  - name: Add information to MOTD
    lineinfile:
      path: /etc/motd
      regexp: '^#(.*)System info:(.*)$'
      line: "#    System info: {{ inventory_hostname }} / {{ansible_product_name}} / {{ansible_lsb.description}}"

  - name: Configure hostname in hosts file
    lineinfile:
      path: /etc/hosts
      regexp: '^127\.0\.1\.1'
      line: "127.0.1.1  {{ inventory_hostname }} cumulus"
      state: present

  - name: Ensure hostname is set correctly
    hostname:
      name: "{{ inventory_hostname }}"
    when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')
